
# 회원 로그인
GET {{url}}/api/login.do?userid=test0223&passwd=1234
Content-Type: application/json


###

# 사용자 토큰 Refresh
POST {{url}}/refreshToken.do
Content-Type: application/json
Access_Token: {{access_token}}
Refresh_Token: {{refresh_token}}

###

# 현장점검 데이터 가져오기
GET {{url}}/api/selectProcField.do?gbn=fd2&idx=309
Content-Type: application/json
Access_Token: {{access_token}}

###

# 현장점검 리스트 데이터 가져오기
GET {{url}}/api/selectProcList.do?gbn=fd2&company=test
Content-Type: application/json
Access_Token: {{access_token}}


